name: IPTV HLS Converter

on:
  workflow_dispatch:

jobs:
  hls:
    runs-on: ubuntu-latest

    steps:
      - name: Install FFmpeg
        run: |
          sudo apt update
          sudo apt install -y ffmpeg

      - name: Create channels
        run: |
          mkdir -p output

          cat > channels.txt <<'EOF'
Bein_News|http://line.trxdnscloud.ru/live/1508358b7d/7b13892f97dc/1917225.ts
Bein_1|http://line.trxdnscloud.ru/live/1508358b7d/7b13892f97dc/1917215.ts
Bein_2|http://line.trxdnscloud.ru/live/1508358b7d/7b13892f97dc/1917214.ts
Bein_3|http://line.trxdnscloud.ru/live/1508358b7d/7b13892f97dc/1917213.ts
Bein_4|http://line.trxdnscloud.ru/live/1508358b7d/7b13892f97dc/1917212.ts
Bein_5|http://line.trxdnscloud.ru/live/1508358b7d/7b13892f97dc/1917211.ts
Bein_6|http://line.trxdnscloud.ru/live/1508358b7d/7b13892f97dc/1917210.ts
Bein_7|http://line.trxdnscloud.ru/live/1508358b7d/7b13892f97dc/1917209.ts
Bein_8|http://line.trxdnscloud.ru/live/1508358b7d/7b13892f97dc/1917208.ts
Athmania_1|http://line.vpntxvpn.ru/live/1508358b7d/7b13892f97dc/1898976.ts
Athmania_2|http://line.vpntxvpn.ru/live/1508358b7d/7b13892f97dc/1898975.ts
Athmania_3|http://line.vpntxvpn.ru/live/1508358b7d/7b13892f97dc/1899054.ts
MBC_2|http://vpn.bimtrex.eu/live/2c16beb3ae/b28582fcb55a/7746.ts
MBC_3|http://vpn.bimtrex.eu/live/2c16beb3ae/b28582fcb55a/7745.ts
MBC_4|http://vpn.bimtrex.eu/live/2c16beb3ae/b28582fcb55a/7744.ts
MBC_5|http://vpn.bimtrex.eu/live/2c16beb3ae/b28582fcb55a/90929.ts
Al_Aoula|http://vpn.bimtrex.eu/live/2c16beb3ae/b28582fcb55a/891367.ts
2M_Maroc|http://vpn.bimtrex.eu/live/2c16beb3ae/b28582fcb55a/6736.ts
Arryadia_HD|http://vpn.bimtrex.eu/live/2c16beb3ae/b28582fcb55a/969051.ts
National_Geo|http://vpn.bimtrex.eu/live/2c16beb3ae/b28582fcb55a/880186.ts
Quran_Kareem|http://vpn.bimtrex.eu/live/2c16beb3ae/b28582fcb55a/2112498.ts
EOF

      - name: Convert TS to HLS
        run: |
          while IFS="|" read -r name url
          do
            mkdir -p output/$name

            ffmpeg -y \
            -i "$url" \
            -c:v copy \
            -c:a aac \
            -f hls \
            -hls_time 6 \
            -hls_list_size 5 \
            -hls_flags delete_segments \
            output/$name/index.m3u8 &

          done < channels.txt

          sleep 30

      - name: Upload files
        uses: actions/upload-artifact@v4
        with:
          name: HLS-CHANNELS
          path: output
