name: Generate IPTV Playlist

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *'  # يعمل يوميًا تلقائيًا لتحديث القائمة
  workflow_dispatch:      # يسمح بتشغيله يدويًا في أي وقت

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run Playlist Generator
        run: python generate.py

      - name: Upload Artifacts (Downloadable Files)
        uses: actions/upload-artifact@v4
        with:
          name: iptv-m3u-files
          path: |
            playlist.m3u
            playlist.m3u8

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          keep_files: false
